#!/usr/bin/env bash
# Displays a list of currently running processes.
# show all processes, fo all users, including those
# which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

ps -auxf
